### ISSUE TITLE
Provide option to enable/disable floating of Section view

### ISSUE THREAD

**Issue by stanydsouzall** [GONZALEZD/cupertino_listview#6]
Provide option to enable/disable floating of Section view. Just same as tableview type in iOS is of plain and grouped type.

**Comment by nissaba** [comment]
Bump!! Me 2 I would needs this. I need to do a list view and we need to use semi-tranparent rows and header to have the background peek thru the list. And as you can guess having the header background at opacity at 0.32 when the cell row goes under the header it make for really bad visuals. 

I am comming from the iOS native background and this Widget is as close I can get the my beloved TableView from UIKit. But I really need to be able to have. the headers not stick at the top.

**Comment by GONZALEZD** [comment]
Hi,
What you both describe is using the List (or SliverList) widget. I don't see the needs to provide this usecase, because it will be an non-optimized and dirty version of the List widget.

To provide the behaviour you want, you can create a custom widget wrapping either a List or CupertinoListView, depending of the data to display. Or having a behaviour that fit your needs.

Regards,
David.
